### ISSUE TITLE
Migrate repository to AztecProtocol

### ISSUE THREAD

**Issue by Savio-Sou** [AztecProtocol/noirenberg#88]
This repository is a boilerplate for the E2E workflow covering:
1. NoirJS compile
2. NoirJS execute
3. bb.js prove
4. bb.js Solidity verifier (generation + deploy)
5. Solidity verify

Following https://github.com/noir-lang/noir/issues/4960, Noir covers up to Step 2 of the workflow and proving backends tackle the rest.

This repository should hence be migrated to [AztecProtocol](https://github.com/AztecProtocol/), where it can integrate and test with bb.js more easily.

## Open questions

- Should this migrate as a standalone repository in AztecProtocol, or into AztecProtocol/aztec-packages?
  - Latter enables CI tests with bb.js changes, but would it negatively impact DevEx of the boilerplate itself (e.g. harder to clone)?

**Comment by critesjosh** [comment]
@signorecello looks like this has been migrated. Do we still want/need to use this repo for testing around steps 3-5 mentioned above? Are those being tested elsewhere?

**Comment by Savio-Sou** [comment]
bb.js tests should already exist in aztec-packages (or should exist there if not), we can close this as completed. Thanks for the work!
